# Generated by Django 2.2.5 on 2019-09-12 08:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('attribute', models.CharField(default='Default', max_length=200)),
                ('size', models.CharField(max_length=100, null=True)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='write here', max_length=200)),
                ('ProductType', models.CharField(default='write type here, i.e is it a cellphone, radio etc.', max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Description', models.TextField(default='follow the campus shop guides for creating your description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='Category_image')),
            ],
            options={
                'verbose_name': 'product_category',
                'verbose_name_plural': 'categories',
                'ordering': ['CategoryName'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Ordered', models.DateTimeField(auto_now=True)),
                ('CartOrder', models.ManyToManyField(related_name='cartnumbers', to='ecommerce.OrderItem')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='profiles.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_Name', models.CharField(max_length=30, unique=True)),
                ('Description', models.TextField(max_length=200)),
                ('Street_Address', models.CharField(default='1 Jorissen Street', max_length=50)),
                ('Suburb', models.CharField(default='Braamforntein', max_length=30)),
                ('City', models.CharField(default='Johannesburg', max_length=30)),
                ('ZipCode', models.CharField(blank=True, max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Type', models.CharField(choices=[('CASUAL', 'Casual Seller'), ('PROFESSIONAL', 'Professional')], max_length=50, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='profiles.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddImage', models.ImageField(upload_to='Product_image')),
                ('Stock', models.IntegerField(default=1)),
                ('name', models.CharField(default='write here', max_length=200)),
                ('ToBeDelivered', models.IntegerField(default=0)),
                ('Delivered', models.IntegerField(default=0)),
                ('Sales', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('sizes', models.CharField(max_length=100, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Shop'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.Product'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PendingOrders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None)),
                ('PendingOrderIds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None)),
                ('PendingProductIds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None)),
                ('PendingObjectId', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None)),
                ('AcceptedOrders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None)),
                ('AcceptedUsersIds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None)),
                ('AcceptedProductIds', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None)),
                ('AcceptedObjectId', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None)),
                ('shop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ecommerce.Shop')),
            ],
        ),
    ]
