# Generated by Django 2.0.13 on 2019-06-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20190628_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shoppingcartorder',
            name='CartOrder',
        ),
        migrations.RemoveField(
            model_name='shoppingcartorder',
            name='Owner',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShoppingCartOrder',
        ),
    ]
