# Generated by Django 2.0.13 on 2019-06-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('ecommerce', '0004_auto_20190628_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['CategoryName'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderExists', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='write here', max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Stock', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='Product_image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Ordered', models.DateTimeField(auto_now=True)),
                ('CartOrder', models.ManyToManyField(related_name='cartnumbers', to='ecommerce.OrderItem')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='profiles.Account')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.Product'),
        ),
    ]
