# Generated by Django 2.0.13 on 2019-06-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20190628_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['CategoryName'], 'verbose_name': 'product_category', 'verbose_name_plural': 'categories'},
        ),
    ]
