# Generated by Django 2.0.13 on 2019-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductType',
            field=models.CharField(default='write type here, i.e is it a cellphone, radio etc.', max_length=200),
        ),
    ]
