# Generated by Django 2.0.13 on 2019-06-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_product_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(default='follow the campus shop guides for creating your description'),
        ),
    ]
