# Generated by Django 2.0.13 on 2019-07-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='profiles.Account'),
        ),
    ]
