# Generated by Django 2.0.13 on 2019-07-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20190701_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddImage', models.ImageField(blank=True, upload_to='Product_image')),
                ('name', models.CharField(default='write here', max_length=200)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
    ]
