# Generated by Django 2.0.13 on 2019-07-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20190704_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='Delivery_Location',
        ),
        migrations.AddField(
            model_name='shop',
            name='City',
            field=models.CharField(default='Johannesburg', max_length=30),
        ),
        migrations.AddField(
            model_name='shop',
            name='Street_Address',
            field=models.CharField(default='1 Jorissen Street', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='Suburb',
            field=models.CharField(default='Braamforntein', max_length=30),
        ),
        migrations.AddField(
            model_name='shop',
            name='ZipCode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='AddImage',
            field=models.ImageField(upload_to='Product_image'),
        ),
    ]
