# Generated by Django 2.0.13 on 2019-07-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='Category_image'),
        ),
    ]
