# Generated by Django 2.0.13 on 2019-07-25 21:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_auto_20190725_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='AcceptedOrders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='AcceptedProductIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='AcceptedUsersIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='PendingOrders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='PendingProductIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ecommerce.Shop'),
        ),
    ]
