# Generated by Django 2.0.13 on 2019-07-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20190725_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ecommerce.Shop'),
        ),
    ]
