# Generated by Django 2.0.13 on 2019-07-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20190728_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='OrderExists',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Delivered',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Sales',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ToBeDelivered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='attribute',
            field=models.CharField(default='Default', max_length=200),
        ),
        migrations.AddField(
            model_name='productimage',
            name='Delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='Sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='productimage',
            name='ToBeDelivered',
            field=models.IntegerField(default=0),
        ),
    ]
