# Generated by Django 2.0.13 on 2019-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20190730_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Type',
            field=models.CharField(choices=[('CASUAL', 'Casual Seller'), ('PROFESSIONAL', 'Professional')], max_length=50, null=True),
        ),
    ]
