# Generated by Django 2.0.13 on 2019-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='sizes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
